export const IRAQI_GOVERNORATES: { en: string; ar: string }[] = [
  { en: "Baghdad", ar: "بغداد" },
  { en: "Basra", ar: "البصرة" },
  { en: "Nineveh", ar: "نينوى" },
  { en: "Erbil", ar: "أربيل" },
  { en: "Sulaymaniyah", ar: "السليمانية" },
  { en: "Duhok", ar: "دهوك" },
  { en: "Kirkuk", ar: "كركوك" },
  { en: "Najaf", ar: "النجف" },
  { en: "Karbala", ar: "كربلاء" },
  { en: "Babil", ar: "بابل" },
  { en: "Wasit", ar: "واسط" },
  { en: "Maysan", ar: "ميسان" },
  { en: "Dhi Qar", ar: "ذي قار" },
  { en: "Muthanna", ar: "المثنى" },
  { en: "Qadisiyyah", ar: "القادسية" },
  { en: "Diyala", ar: "ديالى" },
  { en: "Anbar", ar: "الأنبار" },
  { en: "Saladin", ar: "صلاح الدين" },
];